export const ADD_TODO = 'ADD_TODO';
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO';
export const CLEAN_CURRENT_TODO = 'CLEAN_CURRENT_TODO';

export const SEND_TODO_START = 'SEND_TODO_START';
export const SEND_TODO_COMPLETE = 'SEND_TODO_COMPLETE';
export const SEND_TODO_FAIL = 'SEND_TODO_FAIL';
